# Workflow derived from https://github.com/d-morrison/gha/blob/main/examples/check-non-standard-chars.yml
name: Check Non-Standard Characters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: d-morrison/gha/.github/workflows/check-non-standard-chars.yml@v1
